version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/native_core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/ml_sidecar"
    schedule:
      interval: "weekly"
